language: scala

scala:
#   - 2.10.6
#  - 2.11.12
  - 2.12.11
  - 2.13.2
jdk:
  - openjdk8

git:
  depth: 3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-compiler

before_script: # https://github.com/travis-ci/travis-ci/issues/7703
  - sudo chmod +x /usr/local/bin/sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
